@echo off
rem ====================================================================
rem BuildEdSharp.cmd - x64 build for EdSharp.exe (v5 modernization).
rem
rem   1. EdSharp.dll -- JScript .NET scripting host, from EdSharp.js by
rem      jsc.exe. Loaded at run time by reflection (Assembly.LoadFrom),
rem      so csc.exe does NOT /reference it (same base name as the exe).
rem   2. EdSharp.exe -- the WinForms app, from EdSharp.cs by csc.exe,
rem      x64, with the manifest and (if present) icon.
rem
rem Bare compilers, no MSBuild/NuGet: jsc.exe and csc.exe both ship with
rem the .NET Framework; csc is also available, newer, from VS Build
rem Tools. Mirrors the DbDo build model.
rem ====================================================================
setlocal enableextensions enabledelayedexpansion
pushd "%~dp0"

set "log=BuildEdSharp.log"
echo EdSharp build log > "!log!"
echo Started %DATE% %TIME% >> "!log!"

if not exist "EdSharp.cs" echo ERROR: EdSharp.cs not found.& popd & exit /b 1
if not exist "Lbc.cs" echo ERROR: Lbc.cs not found.& popd & exit /b 1
if not exist "Say.cs" echo ERROR: Say.cs not found.& popd & exit /b 1
if not exist "Inix.cs" echo ERROR: Inix.cs not found.& popd & exit /b 1
if not exist "KeyMap.cs" echo ERROR: KeyMap.cs not found.& popd & exit /b 1
if not exist "EdSharp.js" echo ERROR: EdSharp.js not found.& popd & exit /b 1
if not exist "EdSharp.manifest" echo ERROR: EdSharp.manifest not found.& popd & exit /b 1

rem ---- version: version.txt is the SINGLE source of truth ----
rem The version lives in version.txt: one line, nothing else.  It is incremented
rem here, BEFORE anything is compiled, because both the program and the installer
rem bake the number in:
rem   * this script generates Version.cs from it, so the running program reports it
rem   * EdSharp_Setup.iss reads version.txt directly (see its #define AppVersion), so the
rem     installer is stamped with it
rem   * tagRelease tags the release with it
rem All three therefore always agree, which is what Elevate Version (F11) needs.
rem The .iss contains NO version number, so an old copy of it cannot rewind one.
rem
rem Pass "nobump" to recompile without taking a new number: BuildEdSharp.cmd nobump
if not exist "version.txt" (
  echo ERROR: version.txt not found. It must hold the current version, e.g. 1.0.0
  echo ERROR: version.txt not found. >> "!log!"
  popd
  exit /b 1
)
set "ver="
set /p ver=<version.txt
rem strip stray spaces; a version number never contains one
set "ver=!ver: =!"
if "!ver!"=="" (
  echo ERROR: version.txt is empty.
  echo ERROR: version.txt is empty. >> "!log!"
  popd
  exit /b 1
)

if /i "%~1"=="nobump" (
  echo Version: !ver! ^(nobump: keeping the current number^)
  echo Version: !ver! ^(nobump^) >> "!log!"
) else (
  call :takeNextVersion
)

rem ---- generate Version.cs from version.txt ----
rem Version.cs is generated output: do not edit it, and keep it out of git.
> Version.cs echo // Generated by BuildEdSharp.cmd from version.txt.  Do not edit; do not commit.
>> Version.cs echo public static class BuildVersion
>> Version.cs echo {
>> Version.cs echo     public const string Version = "!ver!";
>> Version.cs echo }

rem ---- locate csc.exe: prefer Roslyn (latest C#), fall back to Framework ----
set "csc="
for %%p in (
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
  "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
  "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe"
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
  "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
  "%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\csc.exe"
) do (if not defined csc if exist %%p set "csc=%%~p")
if not defined csc echo ERROR: No csc.exe found. Install VS Build Tools or repair .NET Framework.& popd & exit /b 1
echo C# compiler: !csc! >> "!log!"

rem ---- locate jsc.exe (Framework only; no Roslyn JScript) ----
set "jsc="
if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\jsc.exe" set "jsc=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\jsc.exe"
if not defined jsc if exist "%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\jsc.exe" set "jsc=%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\jsc.exe"
if not defined jsc echo ERROR: No jsc.exe found (repair .NET Framework).& popd & exit /b 1
echo JScript compiler: !jsc! >> "!log!"

rem ---- locate UIA reference assemblies (for the UIA-notification work) ----
rem Not referenced by this minimal baseline yet, but probed here so the
rem command line is ready when the speech subsystem moves to UIA. Probe
rem the .NET 4.8 Developer Pack first, then the GAC runtime images.
set "uiaProv="
set "uiaTypes="
set "refDir=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8"
if exist "!refDir!\UIAutomationProvider.dll" set "uiaProv=!refDir!\UIAutomationProvider.dll"
if exist "!refDir!\UIAutomationTypes.dll"    set "uiaTypes=!refDir!\UIAutomationTypes.dll"
if not defined uiaProv if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll" set "uiaProv=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll"
if not defined uiaTypes if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll" set "uiaTypes=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll"
if not defined uiaProv echo ERROR: UIAutomationProvider.dll not found; install the .NET 4.8 Developer Pack.& popd & exit /b 1
if not defined uiaTypes echo ERROR: UIAutomationTypes.dll not found; install the .NET 4.8 Developer Pack.& popd & exit /b 1
echo UIAutomationProvider: !uiaProv! >> "!log!"
echo UIAutomationTypes: !uiaTypes! >> "!log!"

rem ---- x64 NVDA controller client (runtime-only, optional) ----
rem nvdaControllerClient.dll drives NVDA's extra-speech announcements. It is
rem NOT needed to build or to run the editor (normal screen-reader access
rem works without it); only the optional spoken status messages use it. The
rem 32-bit nvdaControllerClient32.dll from older EdSharp will not load in an
rem x64 process. To enable it, drop the x64 nvdaControllerClient.dll beside
rem EdSharp.exe; get it from the NVDA controllerClient package at
rem https://www.nvaccess.org/ (Developer downloads).
if exist "nvdaControllerClient.dll" (echo NVDA controller client present.) else (echo NVDA controller client absent ^(optional, runtime only^).)

rem ---- compile EdSharp.js -> EdSharp.dll (JScript .NET) ----
echo Compiling EdSharp.js -^> EdSharp.dll ...
if exist EdSharp.dll del /f /q EdSharp.dll
"!jsc!" /nologo /target:library /platform:anycpu /out:EdSharp.dll EdSharp.js >> "!log!" 2>&1
if errorlevel 1 goto failed
echo   EdSharp.dll built.

rem ---- best-effort: fetch the encoding-detection library (Ude.dll) ----
rem Referenced by csc at build time and loaded beside EdSharp.exe at run time.
rem Never fails the build: if Ude.dll is absent, the compile drops the HAVEUDE
rem symbol and content detection degrades to byte-order-mark detection with a
rem UTF-8-with-BOM default (BOM-less non-UTF-8 files are not auto-detected).
if exist "FetchUde.ps1" (
  echo Checking encoding-detection library ^(Ude.dll, best-effort^)... >> "!log!"
  powershell -NoProfile -ExecutionPolicy Bypass -File "FetchUde.ps1" >> "!log!" 2>&1
)
set "udeRef="
set "udeDef="
if exist "Ude.dll" set "udeRef=/reference:Ude.dll"
if exist "Ude.dll" set "udeDef=/define:HAVEUDE"
if exist "Ude.dll" (echo Ude.dll present - content encoding detection enabled. >> "!log!") else (echo Ude.dll absent - BOM detection + UTF-8-BOM default only. >> "!log!")

rem ---- compile EdSharp.cs -> EdSharp.exe (x64) ----
echo Compiling EdSharp.cs -^> EdSharp.exe ...
if exist EdSharp.exe del /f /q EdSharp.exe
set "icon="
if exist EdSharp.ico set "icon=/win32icon:EdSharp.ico"
"!csc!" /nologo /target:winexe /platform:anycpu /optimize+ !udeDef! %icon% /win32manifest:EdSharp.manifest /reference:"Tektosyne.dll" /reference:"Microsoft.VisualBasic.dll" /reference:"Microsoft.CSharp.dll" /reference:"!uiaProv!" /reference:"!uiaTypes!" !udeRef! /out:EdSharp.exe Version.cs EdSharp.cs Lbc.cs Say.cs Inix.cs Web.cs Jaws.cs KeyMap.cs >> "!log!" 2>&1
if errorlevel 1 goto failed

rem ---- native pre-JIT (ngen) is handled by the INSTALLER, not here ----
rem EdSharp.exe is a managed .NET assembly; the CLR JIT-compiles it at launch.
rem EdSharp_Setup.iss runs "ngen install" against the INSTALLED copy in Program
rem Files (elevated, where it actually takes effect) to give a precompiled native
rem image for faster startup.  Running ngen here, in the build folder and usually
rem without admin, did nothing useful for the installed program, so it was removed.
)

rem ---- best-effort: fetch any MISSING third-party Convert tools ----
rem Only downloads tools that are absent; never fails the build. Edit the
rem $tools table in FetchConvertTools.ps1 to adjust URLs/versions, or delete
rem that file to disable this step.
if exist "FetchConvertTools.ps1" (
  echo Checking third-party Convert tools ^(best-effort, automatic^).  "present" = already in this folder, nothing to download; only MISSING tools are fetched, and any that fail to download are retried on the next build. >> "!log!"
  powershell -NoProfile -ExecutionPolicy Bypass -File "FetchConvertTools.ps1" >> "!log!" 2>&1
)

echo.
echo Build complete:
echo   EdSharp.exe  -- the application (x64)
echo   EdSharp.dll  -- JScript .NET scripting host
echo. >> "!log!"
echo BUILD COMPLETE: EdSharp.exe and EdSharp.dll built successfully. >> "!log!"
echo Finished %DATE% %TIME% >> "!log!"
popd & endlocal & exit /b 0

:failed
echo. >> "!log!"
echo BUILD FAILED - compile errors are listed above in this log. >> "!log!"
echo.
echo BUILD FAILED. Errors from %log%:
type "!log!" | findstr /C:": error" /C:"error CS" /C:"error JS"
popd & endlocal & exit /b 1

:takeNextVersion
rem ---------------------------------------------------------------------------
rem Take the next version number: increment the last dotted part of !ver!.
rem
rem This makes NO network call.  An earlier version asked GitHub whether the number
rem was already taken -- but gh has no timeout, so a slow or unreachable network hung
rem the build with no message and no way to interrupt it.  A build script must never
rem wait on the network.  tagRelease does the "already released" check instead: that
rem is where a network call belongs, and where a stall is visible and interruptible.
rem
rem This runs as a subroutine rather than inside a parenthesised ( ) block, so each
rem line is parsed on its own -- avoiding the block-parsing traps batch has inside ( ).
rem ---------------------------------------------------------------------------
set "p1=" & set "p2=" & set "p3=" & set "p4="
set "new="
for /f "tokens=1-4 delims=." %%a in ("!ver!") do (
  set "p1=%%a" & set "p2=%%b" & set "p3=%%c" & set "p4=%%d"
)
if defined p4 (
  set /a p4=p4+1
  set "new=!p1!.!p2!.!p3!.!p4!"
) else if defined p3 (
  set /a p3=p3+1
  set "new=!p1!.!p2!.!p3!"
) else if defined p2 (
  set "new=!p1!.!p2!.1"
) else (
  set "new=!p1!.0.1"
)
if not defined new (
  echo ERROR: could not work out the next version from "!ver!".
  echo ERROR: could not work out the next version from "!ver!". >> "!log!"
  goto :eof
)
> version.txt echo !new!
echo Version: !ver! -^> !new!
echo Version: !ver! -^> !new! >> "!log!"
set "ver=!new!"
goto :eof
