@echo off
rem ===================================================================
rem build.cmd -- build EdSharp against the Homer Development Kit.
rem
rem This is the kit contract: find the kit, refuse an old one, step the
rem version, refresh the kit's scripts, put the files into the Homer
rem encoding, speak any tutorial that has no audio -- then hand the
rem compiling and the installer to build.ps1, which carries
rem EdSharp's own particulars (the JScript.NET side, the NuGet packages,
rem the conversion tools).
rem
rem   build            step the version, then build
rem   build nobump     keep the current number
rem
rem Everything is logged to logs\EdSharp-build-<date>-<time>.log.
rem ===================================================================

setlocal enabledelayedexpansion
cd /d "%~dp0"

set "app=EdSharp"
for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmmss"') do set "sStamp=%%i"
if not exist "%~dp0logs" mkdir "%~dp0logs"
set "log=%~dp0logs\%app%-build-%sStamp%.log"
rem THE START AND END LINES CARRY AN ISO 8601 TIME (HomerDev 1.43.21), with
rem the UTC offset, from PowerShell rather than %DATE% %TIME%, whose form
rem follows the regional settings; and they name the event and its result as
rem every Homer log does.
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "Get-Date -Format 'yyyy-MM-ddTHH:mm:ss.fffzzz'"`) do set "sIso=%%i"
> "%log%" echo %sIso% INFO  build start app=%app%
echo Script: %~f0>> "%log%"
echo Folder: %CD%>> "%log%"
echo Command line: %0 %*>> "%log%"
echo Build log: %log%

rem ---- the Homer Development Kit -------------------------------------
set "homerDev="
if defined HomerDev if exist "%HomerDev%\exec\CSharp\Lbc.cs" set "homerDev=%HomerDev%"
if not defined homerDev if exist "C:\HomerDev\exec\CSharp\Lbc.cs" set "homerDev=C:\HomerDev"
if not defined homerDev if exist "%CD%\exec\CSharp\Lbc.cs" set "homerDev=%CD%"
if not defined homerDev (
  echo EdSharp needs the Homer Development Kit and cannot find it.
  echo Unzip HomerDev.zip into C:\HomerDev, or set the HomerDev environment variable.
  echo ERROR: no kit found.>> "%log%"
  goto :failed
)
set "homerVer=0.0.0"
if exist "!homerDev!\version.txt" set /p homerVer=<"!homerDev!\version.txt"
set "kitNeeded=1.54.0"
powershell -NoProfile -Command "if ([version]'!homerVer!' -lt [version]'!kitNeeded!') { exit 1 } else { exit 0 }" >nul
if errorlevel 1 (
  echo EdSharp needs HomerDev !kitNeeded! or later, and the kit is !homerVer!.
  echo Unzip HomerDev.zip into C:\HomerDev, then build again.
  echo ERROR: kit !homerVer! is older than !kitNeeded!.>> "%log%"
  goto :failed
)
echo Kit: !homerDev! version !homerVer!
echo Kit: !homerDev! version !homerVer!>> "%log%"

rem ---- version: version.txt is the single source of truth -------------
rem The number used to live as AppVersion in the .iss and was derived from
rem the release tags on the remote. It lives here now, as it does in every
rem Homer app, and version.txt never leaves this machine.
if not exist "version.txt" (
  > version.txt echo 5.0.0
  echo No version.txt here, so it was created holding 5.0.0.
  echo Created version.txt holding 5.0.0>> "%log%"
)
set "ver="
set /p ver=<version.txt
set "ver=!ver: =!"
if "!ver!"=="" (
  echo ERROR: version.txt is empty.
  echo ERROR: version.txt is empty.>> "%log%"
  goto :failed
)

rem THE VERSION MUST BE THIS APP'S. A kit unarchived into the app's folder put
rem the kit's version.txt in place of the app's (6 October 2026: 1.53.2 where
rem 1.0.228 belonged), and the next build would have bumped the wrong series.
rem The last published tag is the app's own number: when version.txt's first two
rem parts differ from the tag's, the tag wins, and the log says so.
set "tagVer="
for /f "usebackq delims=" %%t in (`git describe --tags --abbrev^=0 2^>nul`) do set "tagVer=%%t"
set "tagVer=!tagVer:v=!"
if not "!tagVer!"=="" (
  for /f "tokens=1,2 delims=." %%a in ("!ver!") do set "verSeries=%%a.%%b"
  for /f "tokens=1,2 delims=." %%a in ("!tagVer!") do set "tagSeries=%%a.%%b"
  if not "!verSeries!"=="!tagSeries!" (
    echo version.txt held !ver!, not this app's series; the last published tag is !tagVer!, so that is the version now.
    echo version.txt held !ver!, not this app's series; set to the last published tag !tagVer! >> "!log!"
    > version.txt echo !tagVer!
    set "ver=!tagVer!"
  )
)
if /i "%~1"=="nobump" goto :keepVersion
call :takeNextVersion
goto :haveVersion

:keepVersion
echo Version: !ver! ^(nobump: keeping the current number^)
echo Version: !ver! ^(nobump^)>> "%log%"

:haveVersion

rem ---- generate Version.cs from version.txt ---------------------------
rem Generated output: do not edit it, and do not commit it.
> Version.cs echo // Generated by build.cmd from version.txt.  Do not edit; do not commit.
>> Version.cs echo public static class BuildVersion
>> Version.cs echo {
>> Version.cs echo     public const string Version = "!ver!";
>> Version.cs echo }
echo Wrote Version.cs for !ver!>> "%log%"

rem ---- the kit's scripts, refreshed into scripts\ every build ---------
rem One source of truth: a fix in the kit reaches EdSharp on its next
rem build, and nothing here is edited in place.
if not exist "scripts" mkdir "scripts"
for %%F in (buildTutorials.cmd buildTutorials.ps1 check.cmd check.py checkTutorial.cmd checkTutorial.py finish.cmd fixEncoding.cmd fixEncoding.py installCommon.cmd installOllama.cmd installScreenReaderSupport.cmd makeTutorials.cmd makeTutorials.py push.cmd release.cmd release.ps1 tidy.cmd tidy.py unpushed.cmd unpushed.py) do (
  if exist "!homerDev!\scripts\%%F" copy /y "!homerDev!\scripts\%%F" scripts\ >nul
)
rem Retired kit scripts, and EdSharp's own earlier editions of what the kit
rem now does. Named here as well as in migrateEdSharp, so a folder that
rem still carries one is cleaned by the next build. Since kit 1.42 the kit's
rem scripts have plain names -- checkHomerApp is check, gitPush is push,
rem gitUnpushed is unpushed, homerFinish is finish, homerInstall is
rem installCommon, homerTidy is tidy, tagRelease is release -- and the old
rem copies go too, so an old name typed from habit fails at once instead of
rem running a stale tool.
for %%F in (checkHomerApp.cmd checkHomerApp.py gitPush.cmd gitUnpushed.cmd gitUnpushed.py homerFinish.cmd homerInstall.cmd homerTidy.cmd homerTidy.py tagRelease.cmd tagRelease.ps1 cleanDir.cmd cleanDir.py gitRelease.cmd homerPolicy.py installTools.cmd sayTutorial.cmd sayTutorial.py tidyRepo.cmd tidyRepo.py moveNotes.cmd moveNotes.py repoPolicy.py restoreMissing.cmd restoreMissing.py auditEdSharp.cmd auditEdSharp.py summarizeSetup.cmd summarizeSetup.ps1 prepareAuditFixes.cmd applyConvertPolicy.cmd applyConvertPolicy.py dropLatexJawsKeys.cmd dropLatexJawsKeys.py) do (
  if exist "scripts\%%F" del /q "scripts\%%F" && echo Removed retired scripts\%%F>> "%log%"
)
echo Refreshed the kit's scripts into scripts\>> "%log%"

rem ---- carried over to the Homer layout (September 2026) --------------
rem THE KIT'S CLASSES ARE COMPILED FROM C:\HomerDev\exec\CSharp, so a copy at the
rem top of the project is a stale one waiting to be compiled by mistake.
for %%F in (Elevate.cs Inix.cs KeyMap.cs KeyName.cs Lbc.cs Log.cs Mdi.cs Paths.cs Say.cs Util.cs Web.cs inixVert.cs) do (
  if exist "%%F" if exist "!homerDev!\exec\CSharp\%%F" del /q "%%F" && echo Removed the old top-level %%F; the kit's is compiled instead>> "%log%"
)
rem The root tagRelease pair is the release script's old home; scripts\release
rem is its home now.
for %%F in (tagRelease.cmd tagRelease.ps1) do if exist "%%F" if exist "scripts\release.ps1" del /q "%%F" && echo Removed the old top-level %%F; scripts\release replaces it>> "%log%"
rem GIT STILL SPELLS THREE NAMES THE OLD WAY -- Build.cmd,
rem Build.ps1 and EdSharp_Setup.iss -- because Windows' git treats a
rem change of capitals alone as no change. The file on disk is left exactly as
rem it is (renaming this script while it runs would lose cmd's place in it);
rem only the name git records is corrected, by dropping the old entry and
rem adding the file under its current name.
powershell -NoProfile -Command ^
  "$lTracked = @(git ls-files 2>$null);" ^
  "foreach ($sPair in @('Build.cmd>build.cmd', 'Build.ps1>build.ps1', 'EdSharp_Setup.iss>EdSharp_setup.iss')) {" ^
  "  $sOld, $sNew = $sPair.Split('>');" ^
  "  if (-not ($lTracked -ccontains $sOld)) { continue }" ^
  "  git rm --cached --quiet -- $sOld 2>&1 | Out-Null; git add -- $sNew 2>&1 | Out-Null;" ^
  "  'git now records ' + $sOld + ' as ' + $sNew + ', exit code ' + $LASTEXITCODE" ^
  "}" >> "%log%" 2>&1

rem ---- the project's own files in the Homer encoding ------------------
if exist "scripts\fixEncoding.cmd" (
  echo Putting the project's files into the Homer encoding.
  call "scripts\fixEncoding.cmd" >> "%log%" 2>&1
  set "iEncode=!errorlevel!"
  echo Encoding: fixEncoding exit code !iEncode!>> "%log%"
  rem NOT FATAL, on purpose. On 25 September the kit's fixEncoding.cmd
  rem returned 1 after its Python half had finished cleanly, with a stray
  rem "'*' is not recognized" from the wrapper itself. A build should not
  rem stop because a tidying step tripped over its own command line, but it
  rem should say so rather than log a bare number.
  if not "!iEncode!"=="0" echo NOTE: fixEncoding returned !iEncode!. Its own log in logs\ says what it changed.
)

rem ---- spoken tutorials, for any walk with no audio yet ---------------
rem The walks took the Homer pattern of twelve on 6 October 2026; the one
rem earlier script is retired, and the tool retires its audio.
if exist "help\Tutorial_00_Overview.inix" (
  del /q "help\Tutorial_00_Overview.inix"
  echo Removed the retired walk help\Tutorial_00_Overview.inix >> "%log%"
)
rem -build is an argument of its own: a bare call hands the tool THIS
rem script's arguments through %*, and "nobump" is not a script name.
if exist "help\Tutorial_*.inix" (
  set "tutorialsMissing="
  for %%F in (help\Tutorial_*.inix) do if not exist "help\tutorials\%%~nF.mp3" set "tutorialsMissing=1"
  if defined tutorialsMissing (
    echo Speaking the tutorials that have no audio yet.
    call "scripts\buildTutorials.cmd" -build
    if errorlevel 1 echo WARN: not every tutorial could be spoken. The tutorials log in logs\ says why.
  )
)

rem ---- EdSharp's own build: compile and installer ---------------------
rem build.ps1 carries what is particular to EdSharp: the JScript.NET
rem support assembly, the NuGet packages, the conversion tools, and the
rem Inno Setup run. It compiles against the kit's CSharp folder, which is
rem passed to it rather than looked for twice.
echo Compiling EdSharp !ver!.
rem THE POWERSHELL HALF WRITES INTO THIS LOG TOO. It used to be called with
rem its output going nowhere but the console: a build that failed on 25
rem September left "Build FAILED" in the log and not one word about why,
rem because the reason had scrolled past on screen. Its output is captured
rem here and shown, and the exit code is recorded either way.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0build.ps1" -HomerDev "!homerDev!" -Version "!ver!" -LogFile "%log%" 2>&1
set "iCompile=!errorlevel!"
echo build.ps1 exit code !iCompile!>> "%log%"
if not "!iCompile!"=="0" (
  echo(
  echo ERROR: the build failed. The reason is in %log%.
  goto :failed
)

for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "Get-Date -Format 'yyyy-MM-ddTHH:mm:ss.fffzzz'"`) do set "sIso=%%i"
>> "%log%" echo %sIso% INFO  build end result=succeeded
echo(
echo Built exec\EdSharp.exe and EdSharp_Setup.exe version !ver!.
echo Quick test: exec\EdSharp.exe
echo To publish: scripts\push "message", then scripts\release.
endlocal
exit /b 0

:failed
rem A FAILED BUILD TAKES NO NUMBER (HomerDev 1.43.29). version.txt is stepped
rem when a build begins; when it fails, the number goes back, so the next build
rem takes it again and the release never finds an installer one version behind
rem version.txt (HomerScribe, 28 September 2026: 1.0.260 stepped, the kit not
rem found, the release refused).
if defined verOld if not "!ver!"=="!verOld!" (
  > version.txt echo !verOld!
  >> "%log%" echo Version: restored to !verOld!; a failed build takes no number
)
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "Get-Date -Format 'yyyy-MM-ddTHH:mm:ss.fffzzz'"`) do set "sIso=%%i"
>> "%log%" echo %sIso% ERROR build end result=failed
endlocal
exit /b 1

:takeNextVersion
rem -------------------------------------------------------------------
rem Take the next unused version: increment the last dotted part, and
rem step over any number that already carries a release tag on origin,
rem so a version.txt that has fallen behind cannot mint a spent number.
rem -------------------------------------------------------------------
set "verOld=!ver!"
set "sTagFile=%TEMP%\%app%_tags.txt"
del "!sTagFile!" >nul 2>&1
git ls-remote --tags origin "v*" > "!sTagFile!" 2>> "%log%"
if errorlevel 1 echo WARN: the released tags could not be read, so the next number is taken blindly.>> "%log%"
if errorlevel 1 del "!sTagFile!" >nul 2>&1
rem THE TAG LIST WITH WINDOWS LINE ENDS (1 October 2026). git writes it with
rem LF alone, and findstr /e matches only before a CR LF, so no tag ever
rem matched and no spent number was stepped over: EdSharp's old releases
rem v5.0.32 to v5.0.36 were each chosen again, and each refused as already
rem released. find /v "" rewrites every line with CR LF.
if exist "!sTagFile!" type "!sTagFile!" | find /v "" > "!sTagFile!.crlf"
if exist "!sTagFile!.crlf" move /y "!sTagFile!.crlf" "!sTagFile!" >nul
if exist "!sTagFile!" for /f %%n in ('find /c "refs/tags/" ^< "!sTagFile!"') do echo Released tags on origin: %%n>> "%log%"

:nextCandidate
call :incrementVersion
if not defined new goto :eof
if not exist "!sTagFile!" goto :haveNextVersion
findstr /e /c:"refs/tags/v!ver!" "!sTagFile!" >nul 2>&1
if errorlevel 1 goto :haveNextVersion
echo Version v!ver! is already released; stepping over it.
echo Version v!ver! is already released; stepping over it.>> "%log%"
goto :nextCandidate

:haveNextVersion
del "!sTagFile!" >nul 2>&1
> version.txt echo !ver!
echo Version: !verOld! -^> !ver!
echo Version: !verOld! -^> !ver!>> "%log%"
goto :eof

:incrementVersion
set "p1=" & set "p2=" & set "p3=" & set "p4="
set "new="
for /f "tokens=1-4 delims=." %%a in ("!ver!") do (
  set "p1=%%a" & set "p2=%%b" & set "p3=%%c" & set "p4=%%d"
)
if defined p4 (
  set /a p4=p4+1
  set "new=!p1!.!p2!.!p3!.!p4!"
) else if defined p3 (
  set /a p3=p3+1
  set "new=!p1!.!p2!.!p3!"
) else if defined p2 (
  set "new=!p1!.!p2!.1"
) else (
  set "new=!p1!.0.1"
)
if not defined new (
  echo ERROR: could not work out the next version from "!ver!".
  echo ERROR: could not work out the next version from "!ver!".>> "%log%"
  goto :eof
)
set "ver=!new!"
goto :eof
