clean:
	rmdir /S /Q build
prepare:
	mkdir build
	mkdir build\cs
	mkdir build\vb
recipe3-1:
	csc.exe /t:exe /out:build\cs\recipe3-1.exe 3-1\recipe3-1.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-1.exe 3-1\recipe3-1.vb
recipe3-2:
	csc.exe /t:exe /out:build\cs\recipe3-2.exe 3-2\recipe3-2.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-2.exe 3-2\recipe3-2.vb
recipe3-3:
	csc.exe /t:exe /out:build\cs\recipe3-3.exe 3-3\recipe3-3.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-3.exe 3-3\recipe3-3.vb
recipe3-4:
	csc.exe /t:exe /out:build\cs\recipe3-4.exe 3-4\recipe3-4.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-4.exe 3-4\recipe3-4.vb
recipe3-5:
	csc.exe /t:exe /out:build\cs\recipe3-5.exe 3-5\recipe3-5.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-5.exe 3-5\recipe3-5.vb
recipe3-6:
	csc.exe /t:exe /out:build\cs\recipe3-6.exe 3-6\recipe3-6.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-6.exe 3-6\recipe3-6.vb
recipe3-7:
	csc.exe /t:exe /out:build\cs\recipe3-7.exe 3-7\recipe3-7.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-7.exe 3-7\recipe3-7.vb
recipe3-8:
	csc.exe /t:exe /out:build\cs\recipe3-8.exe 3-8\recipe3-8.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe3-8.exe 3-8\recipe3-8.vb
recipes:  prepare recipe3-1 recipe3-2 recipe3-3 recipe3-4 recipe3-5 recipe3-6 recipe3-7 recipe3-8 
