clean:
	rmdir /S /Q build
prepare:
	mkdir build
	mkdir build\cs
	mkdir build\vb
recipe6-1:
	csc.exe /t:exe /out:build\cs\recipe6-1.exe 6-1\recipe6-1.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-1.exe 6-1\recipe6-1.vb
recipe6-2:
	csc.exe /t:exe /out:build\cs\recipe6-2.exe 6-2\recipe6-2.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-2.exe 6-2\recipe6-2.vb
recipe6-3:
	csc.exe /t:exe /out:build\cs\recipe6-3.exe 6-3\recipe6-3.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-3.exe 6-3\recipe6-3.vb
recipe6-4:
	csc.exe /t:exe /out:build\cs\recipe6-4.exe 6-4\recipe6-4.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-4.exe 6-4\recipe6-4.vb
recipe6-5:
	csc.exe /t:exe /out:build\cs\recipe6-5.exe 6-5\recipe6-5.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-5.exe 6-5\recipe6-5.vb
recipe6-6:
	csc.exe /t:exe /out:build\cs\recipe6-6.exe 6-6\recipe6-6.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-6.exe 6-6\recipe6-6.vb
recipe6-7:
	csc.exe /t:exe /out:build\cs\recipe6-7.exe 6-7\recipe6-7.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-7.exe 6-7\recipe6-7.vb
recipe6-8:
	csc.exe /t:exe /out:build\cs\recipe6-8.exe 6-8\recipe6-8.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-8.exe 6-8\recipe6-8.vb
recipe6-9:
	csc.exe /t:exe /out:build\cs\recipe6-9.exe 6-9\recipe6-9.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-9.exe 6-9\recipe6-9.vb
recipe6-10:
	csc.exe /t:exe /out:build\cs\recipe6-10.exe 6-10\recipe6-10.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-10.exe 6-10\recipe6-10.vb
recipe6-11:
	csc.exe /t:exe /out:build\cs\recipe6-11.exe 6-11\recipe6-11.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-11.exe 6-11\recipe6-11.vb
recipe6-12:
	csc.exe /t:exe /out:build\cs\recipe6-12.exe 6-12\recipe6-12.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-12.exe 6-12\recipe6-12.vb
recipe6-13:
	csc.exe /t:exe /out:build\cs\recipe6-13.exe 6-13\recipe6-13.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-13.exe 6-13\recipe6-13.vb
recipe6-14:
	csc.exe /t:exe /out:build\cs\recipe6-14.exe 6-14\recipe6-14.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-14.exe 6-14\recipe6-14.vb
recipe6-15:
	csc.exe /t:exe /out:build\cs\recipe6-15.exe 6-15\recipe6-15.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-15.exe 6-15\recipe6-15.vb
recipe6-16:
	csc.exe /t:exe /out:build\cs\recipe6-16.exe 6-16\recipe6-16.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-16.exe 6-16\recipe6-16.vb
recipe6-17:
	csc.exe /t:exe /out:build\cs\recipe6-17.exe 6-17\recipe6-17.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-17.exe 6-17\recipe6-17.vb
recipe6-18:
	csc.exe /t:exe /out:build\cs\recipe6-18.exe 6-18\recipe6-18.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-18.exe 6-18\recipe6-18.vb
recipe6-19:
	csc.exe /t:exe /out:build\cs\recipe6-19.exe 6-19\recipe6-19.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-19.exe 6-19\recipe6-19.vb
recipe6-20:
	csc.exe /t:exe /out:build\cs\recipe6-20.exe 6-20\recipe6-20.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-20.exe 6-20\recipe6-20.vb
recipe6-21:
	csc.exe /t:exe /out:build\cs\recipe6-21.exe 6-21\recipe6-21.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-21.exe 6-21\recipe6-21.vb
recipe6-22:
	csc.exe /t:exe /out:build\cs\recipe6-22.exe 6-22\recipe6-22.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-22.exe 6-22\recipe6-22.vb
recipe6-23:
	csc.exe /t:exe /out:build\cs\recipe6-23.exe 6-23\recipe6-23.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-23.exe 6-23\recipe6-23.vb
recipe6-24:
	csc.exe /t:exe /out:build\cs\recipe6-24.exe 6-24\recipe6-24.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-24.exe 6-24\recipe6-24.vb
recipe6-25:
	csc.exe /t:exe /out:build\cs\recipe6-25.exe 6-25\recipe6-25.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe6-25.exe 6-25\recipe6-25.vb
recipes:  prepare recipe6-1 recipe6-2 recipe6-3 recipe6-4 recipe6-5 recipe6-6 recipe6-7 recipe6-8 recipe6-9 recipe6-10 recipe6-11 recipe6-12 recipe6-13 recipe6-14 recipe6-15 recipe6-16 recipe6-17 recipe6-18 recipe6-19 recipe6-20 recipe6-21 recipe6-22 recipe6-23 recipe6-24 recipe6-25
