clean:
	rmdir /S /Q build
prepare:
	mkdir build
	mkdir build\cs
	mkdir build\vb
recipe1-1:
	csc.exe /t:exe /out:build\cs\recipe1-1.exe 1-1\recipe1-1.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-1.exe 1-1\recipe1-1.vb
recipe1-2:
	csc.exe /t:exe /out:build\cs\recipe1-2.exe 1-2\recipe1-2.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-2.exe 1-2\recipe1-2.vb
recipe1-3:
	csc.exe /t:exe /out:build\cs\recipe1-3.exe 1-3\recipe1-3.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-3.exe 1-3\recipe1-3.vb
recipe1-4:
	csc.exe /t:exe /out:build\cs\recipe1-4.exe 1-4\recipe1-4.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-4.exe 1-4\recipe1-4.vb
recipe1-5:
	csc.exe /t:exe /out:build\cs\recipe1-5.exe 1-5\recipe1-5.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-5.exe 1-5\recipe1-5.vb
recipe1-6:
	csc.exe /t:exe /out:build\cs\recipe1-6.exe 1-6\recipe1-6.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-6.exe 1-6\recipe1-6.vb
recipe1-7:
	csc.exe /t:exe /out:build\cs\recipe1-7.exe 1-7\recipe1-7.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-7.exe 1-7\recipe1-7.vb
recipe1-8:
	csc.exe /t:exe /out:build\cs\recipe1-8.exe 1-8\recipe1-8.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-8.exe 1-8\recipe1-8.vb
recipe1-9:
	csc.exe /t:exe /out:build\cs\recipe1-9.exe 1-9\recipe1-9.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-9.exe 1-9\recipe1-9.vb
recipe1-10:
	csc.exe /t:exe /out:build\cs\recipe1-10.exe 1-10\recipe1-10.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-10.exe 1-10\recipe1-10.vb
recipe1-11:
	csc.exe /t:exe /out:build\cs\recipe1-11.exe 1-11\recipe1-11.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-11.exe 1-11\recipe1-11.vb
recipe1-12:
	csc.exe /t:exe /out:build\cs\recipe1-12.exe 1-12\recipe1-12.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-12.exe 1-12\recipe1-12.vb
recipe1-13:
	csc.exe /t:exe /out:build\cs\recipe1-13.exe 1-13\recipe1-13.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-13.exe 1-13\recipe1-13.vb
recipe1-14:
	csc.exe /t:exe /out:build\cs\recipe1-14.exe 1-14\recipe1-14.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-14.exe 1-14\recipe1-14.vb
recipe1-15:
	csc.exe /t:exe /out:build\cs\recipe1-15.exe 1-15\recipe1-15.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-15.exe 1-15\recipe1-15.vb
recipe1-16:
	csc.exe /t:exe /out:build\cs\recipe1-16.exe 1-16\recipe1-16.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-16.exe 1-16\recipe1-16.vb
recipe1-17:
	csc.exe /t:exe /out:build\cs\recipe1-17.exe 1-17\recipe1-17.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-17.exe 1-17\recipe1-17.vb
recipe1-18:
	csc.exe /t:exe /out:build\cs\recipe1-18.exe 1-18\recipe1-18.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-18.exe 1-18\recipe1-18.vb
recipe1-19:
	csc.exe /t:exe /out:build\cs\recipe1-19.exe 1-19\recipe1-19.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-19.exe 1-19\recipe1-19.vb
recipe1-20:
	csc.exe /t:exe /out:build\cs\recipe1-20.exe 1-20\recipe1-20.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-20.exe 1-20\recipe1-20.vb
recipe1-21:
	csc.exe /t:exe /out:build\cs\recipe1-21.exe 1-21\recipe1-21.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-21.exe 1-21\recipe1-21.vb
recipe1-22:
	csc.exe /t:exe /out:build\cs\recipe1-22.exe 1-22\recipe1-22.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-22.exe 1-22\recipe1-22.vb
recipe1-23:
	csc.exe /t:exe /out:build\cs\recipe1-23.exe 1-23\recipe1-23.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-23.exe 1-23\recipe1-23.vb
recipe1-24:
	csc.exe /t:exe /out:build\cs\recipe1-24.exe 1-24\recipe1-24.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-24.exe 1-24\recipe1-24.vb
recipe1-25:
	csc.exe /t:exe /out:build\cs\recipe1-25.exe 1-25\recipe1-25.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-25.exe 1-25\recipe1-25.vb
recipe1-26:
	csc.exe /t:exe /out:build\cs\recipe1-26.exe 1-26\recipe1-26.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe1-26.exe 1-26\recipe1-26.vb
recipes:  prepare recipe1-1 recipe1-2 recipe1-3 recipe1-4 recipe1-5 recipe1-6 recipe1-7 recipe1-8 recipe1-9 recipe1-10 recipe1-11 recipe1-12 recipe1-13 recipe1-14 recipe1-15 recipe1-16 recipe1-17 recipe1-18 recipe1-19 recipe1-20 recipe1-21 recipe1-22 recipe1-23 recipe1-24 recipe1-25 recipe1-26
