clean:
	rmdir /S /Q build
prepare:
	mkdir build
	mkdir build\cs
	mkdir build\vb
recipe4-1:
	csc.exe /t:exe /out:build\cs\recipe4-1.exe 4-1\recipe4-1.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-1.exe 4-1\recipe4-1.vb
recipe4-2:
	csc.exe /t:exe /out:build\cs\recipe4-2.exe 4-2\recipe4-2.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-2.exe 4-2\recipe4-2.vb
recipe4-3:
	csc.exe /t:exe /out:build\cs\recipe4-3.exe 4-3\recipe4-3.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-3.exe 4-3\recipe4-3.vb
recipe4-4:
	csc.exe /t:exe /out:build\cs\recipe4-4.exe 4-4\recipe4-4.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-4.exe 4-4\recipe4-4.vb
recipe4-5:
	csc.exe /t:exe /out:build\cs\recipe4-5.exe 4-5\recipe4-5.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-5.exe 4-5\recipe4-5.vb
recipe4-6:
	csc.exe /t:exe /out:build\cs\recipe4-6.exe 4-6\recipe4-6.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-6.exe 4-6\recipe4-6.vb
recipe4-7:
	csc.exe /t:exe /out:build\cs\recipe4-7.exe 4-7\recipe4-7.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-7.exe 4-7\recipe4-7.vb
recipe4-8:
	csc.exe /t:exe /out:build\cs\recipe4-8.exe 4-8\recipe4-8.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-8.exe 4-8\recipe4-8.vb
recipe4-9:
	csc.exe /t:exe /out:build\cs\recipe4-9.exe 4-9\recipe4-9.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-9.exe 4-9\recipe4-9.vb
recipe4-10:
	csc.exe /t:exe /out:build\cs\recipe4-10.exe 4-10\recipe4-10.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-10.exe 4-10\recipe4-10.vb
recipe4-11:
	csc.exe /t:exe /out:build\cs\recipe4-11.exe 4-11\recipe4-11.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-11.exe 4-11\recipe4-11.vb
recipe4-12:
	csc.exe /t:exe /out:build\cs\recipe4-12.exe 4-12\recipe4-12.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-12.exe 4-12\recipe4-12.vb
recipe4-13:
	csc.exe /t:exe /out:build\cs\recipe4-13.exe 4-13\recipe4-13.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-13.exe 4-13\recipe4-13.vb
recipe4-14:
	csc.exe /t:exe /out:build\cs\recipe4-14.exe 4-14\recipe4-14.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-14.exe 4-14\recipe4-14.vb
recipe4-15:
	csc.exe /t:exe /out:build\cs\recipe4-15.exe 4-15\recipe4-15.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-15.exe 4-15\recipe4-15.vb
recipe4-16:
	csc.exe /t:exe /out:build\cs\recipe4-16.exe 4-16\recipe4-16.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-16.exe 4-16\recipe4-16.vb
recipe4-17:
	csc.exe /t:exe /out:build\cs\recipe4-17.exe 4-17\recipe4-17.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-17.exe 4-17\recipe4-17.vb
recipe4-18:
	csc.exe /t:exe /out:build\cs\recipe4-18.exe 4-18\recipe4-18.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-18.exe 4-18\recipe4-18.vb
recipe4-19:
	csc.exe /t:exe /out:build\cs\recipe4-19.exe 4-19\recipe4-19.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-19.exe 4-19\recipe4-19.vb
recipe4-20:
	csc.exe /t:exe /out:build\cs\recipe4-20.exe 4-20\recipe4-20.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-20.exe 4-20\recipe4-20.vb
recipe4-21:
	csc.exe /t:exe /out:build\cs\recipe4-21.exe 4-21\recipe4-21.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-21.exe 4-21\recipe4-21.vb
recipe4-22:
	csc.exe /t:exe /out:build\cs\recipe4-22.exe 4-22\recipe4-22.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe4-22.exe 4-22\recipe4-22.vb
recipes:  prepare recipe4-1 recipe4-2 recipe4-3 recipe4-4 recipe4-5 recipe4-6 recipe4-7 recipe4-8 recipe4-9 recipe4-10 recipe4-11 recipe4-12 recipe4-13 recipe4-14 recipe4-15 recipe4-16 recipe4-17 recipe4-18 recipe4-19 recipe4-20 recipe4-21 recipe4-22
