clean:
	rmdir /S /Q build
prepare:
	mkdir build
	mkdir build\cs
	mkdir build\vb
recipe5-1:
	csc.exe /t:exe /out:build\cs\recipe5-1.exe 5-1\recipe5-1.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-1.exe 5-1\recipe5-1.vb
recipe5-2:
	csc.exe /t:exe /out:build\cs\recipe5-2.exe 5-2\recipe5-2.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-2.exe 5-2\recipe5-2.vb
recipe5-3:
	csc.exe /t:exe /out:build\cs\recipe5-3.exe 5-3\recipe5-3.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-3.exe 5-3\recipe5-3.vb
recipe5-4:
	csc.exe /t:exe /out:build\cs\recipe5-4.exe 5-4\recipe5-4.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-4.exe 5-4\recipe5-4.vb
recipe5-5:
	csc.exe /t:exe /out:build\cs\recipe5-5.exe 5-5\recipe5-5.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-5.exe 5-5\recipe5-5.vb
recipe5-6:
	csc.exe /t:exe /out:build\cs\recipe5-6.exe 5-6\recipe5-6.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-6.exe 5-6\recipe5-6.vb
recipe5-7:
	csc.exe /t:exe /out:build\cs\recipe5-7.exe 5-7\recipe5-7.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-7.exe 5-7\recipe5-7.vb
recipe5-9:
	csc.exe /t:exe /out:build\cs\recipe5-9.exe 5-9\recipe5-9.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe5-9.exe 5-9\recipe5-9.vb
recipes:  prepare recipe5-1 recipe5-2 recipe5-3 recipe5-4 recipe5-5 recipe5-6 recipe5-7 recipe5-9
