clean:
	rmdir /S /Q build
prepare:
	mkdir build
	mkdir build\cs
	mkdir build\vb
recipe2-1:
	csc.exe /t:exe /out:build\cs\recipe2-1.exe 2-1\recipe2-1.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-1.exe 2-1\recipe2-1.vb
recipe2-2:
	csc.exe /t:exe /out:build\cs\recipe2-2.exe 2-2\recipe2-2.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-2.exe 2-2\recipe2-2.vb
recipe2-3:
	csc.exe /t:exe /out:build\cs\recipe2-3.exe 2-3\recipe2-3.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-3.exe 2-3\recipe2-3.vb
recipe2-4:
	csc.exe /t:exe /out:build\cs\recipe2-4.exe 2-4\recipe2-4.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-4.exe 2-4\recipe2-4.vb
recipe2-5:
	csc.exe /t:exe /out:build\cs\recipe2-5.exe 2-5\recipe2-5.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-5.exe 2-5\recipe2-5.vb
recipe2-6:
	csc.exe /t:exe /out:build\cs\recipe2-6.exe 2-6\recipe2-6.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-6.exe 2-6\recipe2-6.vb
recipe2-7:
	csc.exe /t:exe /out:build\cs\recipe2-7.exe 2-7\recipe2-7.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-7.exe 2-7\recipe2-7.vb
recipe2-8:
	csc.exe /t:exe /out:build\cs\recipe2-8.exe 2-8\recipe2-8.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-8.exe 2-8\recipe2-8.vb
recipe2-9:
	csc.exe /t:exe /out:build\cs\recipe2-9.exe 2-9\recipe2-9.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-9.exe 2-9\recipe2-9.vb
recipe2-10:
	csc.exe /t:exe /out:build\cs\recipe2-10.exe 2-10\recipe2-10.cs
	vbc.exe /r:System.dll /t:exe /out:build\vb\recipe2-10.exe 2-10\recipe2-10.vb
recipes:  prepare recipe2-1 recipe2-2 recipe2-3 recipe2-4 recipe2-5 recipe2-6 recipe2-7 recipe2-8 recipe2-9 recipe2-10
